networks:
  counter-net:

volumes:
  counter-vol:

services:
  web-fe:
    build:
      context: .
    command: python app.py
    ports:
      - target: 8080
        published: 5001
    networks:
      - counter-net

  redis:
    image: redis:alpine
    volumes:
      - counter-vol:/data  # <--- Aqui o volume persiste os dados do Redis
    networks:
      - counter-net
